[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-a_flower_on_a_dark_background_
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-a_flower_on_a_dark_background_
GtkTheme=oomox-a_flower_on_a_dark_background_
IconTheme=oomox-a_flower_on_a_dark_background_
MetacityTheme=oomox-a_flower_on_a_dark_background_
