# Shell variables
# Generated by 'wal'
wallpaper='/home/ibrahim/dotfiles/media/wallpaper4.png'

# Special
background='#0d0518'
foreground='#ede0db'
cursor='#ede0db'

# Colors
color0='#0d0518'
color1='#7D7481'
color2='#A37385'
color3='#D55D92'
color4='#D86A98'
color5='#B5A4A0'
color6='#E0A1B0'
color7='#ede0db'
color8='#a59c99'
color9='#7D7481'
color10='#A37385'
color11='#D55D92'
color12='#D86A98'
color13='#B5A4A0'
color14='#E0A1B0'
color15='#ede0db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
