--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ibrahim/dotfiles/media/wallpaper4.png"

-- Special
background="#0d0518"
foreground="#ede0db"
cursor="#ede0db"

-- Colors
color0="#0d0518"
color1="#7D7481"
color2="#A37385"
color3="#D55D92"
color4="#D86A98"
color5="#B5A4A0"
color6="#E0A1B0"
color7="#ede0db"
color8="#a59c99"
color9="#7D7481"
color10="#A37385"
color11="#D55D92"
color12="#D86A98"
color13="#B5A4A0"
color14="#E0A1B0"
color15="#ede0db"
