[colors.primary]
background = "#0d0518"
foreground = "#ede0db"

[colors.cursor]
text = "#0d0518"
cursor = "#ede0db"

[colors.vi_mode_cursor]
text = "#0d0518"
cursor = "#ede0db"

[colors.search.matches]
foreground = "#0d0518"
background = "#ede0db"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#a59c99"
background = "#ede0db"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d0518"
red = "#7D7481"
green = "#A37385"
yellow = "#D55D92"
blue = "#D86A98"
magenta = "#B5A4A0"
cyan = "#E0A1B0"
white = "#ede0db"

[colors.bright]
black = "#a59c99"
red = "#7D7481"
green = "#A37385"
yellow = "#D55D92"
blue = "#D86A98"
magenta = "#B5A4A0"
cyan = "#E0A1B0"
white = "#ede0db"

[colors.dim]
black = "#ede0db"
red = "#7D7481"
green = "#B5A4A0"
yellow = "#D55D92"
blue = "#D86A98"
magenta = "#A37385"
cyan = "#E0A1B0"
white = "#a59c99"

